#!/bin/sh

cat << SQL | psql -U postgres
CREATE ROLE postqueue PASSWORD 'postqueue' LOGIN;
SQL

cat << SQL | psql -U postgres
CREATE DATABASE postqueue_test WITH OWNER postqueue;
SQL

cat << SQL | psql -U postgres
CREATE DATABASE postqueue WITH OWNER postqueue
SQL
